<Project>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <CaneBuildRoot Condition="'$(CaneBuildRoot)' == ''">$(MSBuildThisFileDirectory)../.tmp/csharp</CaneBuildRoot>
    <BaseIntermediateOutputPath>$(CaneBuildRoot)/obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(CaneBuildRoot)/bin/$(MSBuildProjectName)/</BaseOutputPath>
  </PropertyGroup>
</Project>
